bin/*				usr/bin
src/*.php			usr/share/abraflexi-email-importer
src/Imap2AF/*.php 		usr/lib/abraflexi-email-importer/Imap2AF
i18n/cs_CZ/LC_MESSAGES/*.mo     usr/share/locale/cs_CZ/LC_MESSAGES/
i18n/en_US/LC_MESSAGES/*.mo     usr/share/locale/en_US/LC_MESSAGES/
debian/tmp/composer.json        usr/lib/abraflexi-email-importer/

debian/autoload.php 		usr/lib/abraflexi-email-importer/Imap2AF
abraflexi-email-importer.svg	usr/share/icons/hicolor/scalable/apps/
debian/io.github.vitexsoftware.abraflexi_email_importer.metainfo.xml	usr/share/metainfo/
