<?php

namespace Test\AbraFlexi\Imap2AF;

use AbraFlexi\Imap2AF\Convertor;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-12-02 at 18:09:08.
 */
class ConvertorTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Convertor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Convertor(constant('ISDOC_FILE'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::domPaymentMeansToArray
     */
    public function testdomPaymentMeansToArray() {
        $this->assertEquals(['datSplat' => '2020-12-15'], $this->object->domPaymentMeansToArray($this->object->getXmlDomDocument()->getElementsByTagName('PaymentMeans')));
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::domSuplierToArray
     */
    public function testdomSuplierToArray() {
        $this->assertEquals([
            'nazev' => 'PRAHA12.com s.r.o.',
            'ulice' => 'Komořanská 178/35',
            'mesto' => 'Praha 4',
            'psc' => '14300',
            'tel' => Array(),
            'email' => 'fakturace@praha12.com',
            'stat' => 'code:CZ',
            'ic' => '04700813',
            'dic' => 'CZ04700813',
            'platceDph' => true,
            'typVztahuK' => 'typVztahu.dodavatel'
                ], $this->object->domSuplierToArray($this->object->getXmlDomDocument()->getElementsByTagName('AccountingSupplierParty')));
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::domCustomerToArray
     */
    public function testdomCustomerToArray() {
        $this->assertEquals([
            'nazev' => 'Vítězslav Dvořák',
            'ulice' => 'Melodická 1417/11',
            'mesto' => 'Praha - Stodůlky',
            'psc' => '15800',
            'tel' => Array(),
            'email' => Array(),
            'stat' => 'code:CZ',
            'ic' => Array(),
            'dic' => Array(),
            'platceDph' => true,
                ], $this->object->domCustomerToArray($this->object->getXmlDomDocument()->getElementsByTagName('AccountingCustomerParty')));
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::getInvoiceSuplier
     */
    public function testgetInvoiceSuplier() {
        $this->assertEquals([
            'nazev' => 'PRAHA12.com s.r.o.',
            'ulice' => 'Komořanská 178/35',
            'mesto' => 'Praha 4',
            'psc' => '14300',
            'tel' => Array(),
            'email' => 'fakturace@praha12.com',
            'stat' => 'code:CZ',
            'ic' => '04700813',
            'dic' => 'CZ04700813',
            'platceDph' => true,
            'typVztahuK' => 'typVztahu.dodavatel'
                ], $this->object->getInvoiceSuplier());
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::domTaxTotalToArray
     */
    public function testdomTaxTotalToArray() {
//        $this->assertEquals([], $this->object->domTaxTotalToArray());
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::domInvoiceToArray
     */
    public function testdomInvoiceToArray() {
        $this->assertEquals([
            'id' => 'ext:fc:VF2022648',
            'cisDosle' => 'VF2022648',
            'uuid' => '281A61D4-EBC2-E961-E033-A27486040088',
            'datVyst' => '2020-12-01',
            'poznam' => 'Tržby z prodeje služeb',
            'popis' => 'Tržby z prodeje služeb',
            'mena' => 'code:CZK',
            'typDokl' => 'code:FAKTURA'
                ], $this->object->domInvoiceToArray($this->object->getXmlDomDocument()->getElementsByTagName('Invoice')));
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::invoiceSuplier
     */
    public function testinvoiceSuplier() {
        $this->assertEquals([
            'nazev' => 'PRAHA12.com s.r.o.',
            'ulice' => 'Komořanská 178/35',
            'mesto' => 'Praha 4',
            'psc' => '14300',
            'tel' => Array(),
            'email' => 'fakturace@praha12.com',
            'stat' => 'code:CZ',
            'ic' => '04700813',
            'dic' => 'CZ04700813',
            'platceDph' => true,
            'typVztahuK' => 'typVztahu.dodavatel'
                ], $this->object->invoiceSuplier());
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::invoiceCustomer
     */
    public function testinvoiceCustomer() {
        $this->assertEquals([
            'nazev' => 'Vítězslav Dvořák',
            'ulice' => 'Melodická 1417/11',
            'mesto' => 'Praha - Stodůlky',
            'psc' => '15800',
            'tel' => Array(),
            'email' => Array(),
            'stat' => 'code:CZ',
            'ic' => Array(),
            'dic' => Array(),
            'platceDph' => true,
                ], $this->object->invoiceCustomer());
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::paymentMeans
     */
    public function testpaymentMeans() {
        $this->assertEquals(['datSplat' => '2020-12-15'], $this->object->paymentMeans());
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::invoiceItems
     */
    public function testinvoiceItems() {
        $this->assertEquals([[
        'typPolozkyK' => 'typPolozky.katalog',
        'ucetni' => true,
        'typCenyDphK' => 'typCeny.sDph',
        'typSzbDphK' => 'typSzbDph.dphZakl',
        'kratkyPopis' => '',
        'nazev' => 'Tarif WiFi Max 60/20 pro členy 12/2020',
        'cenaMj' => '349.000000',
        'sumCelkem' => '349.0',
        'sumZkl' => 288.43,
        'nakupCena' => 288.43,
        'cenaZaklVcDph' => 349.0,
        'dan' => 60.57,
        'mnozMj' => '1.0',
        'stavMJ' => '1.0',
        'jednotka' => 'MES',
        'sumDph' => '60.57',
            ]], $this->object->invoiceItems());
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::invoiceInfo
     */
    public function testinvoiceInfo() {
        $this->assertEquals([
            'id' => 'ext:fc:VF2022648',
            'cisDosle' => 'VF2022648',
            'uuid' => '281A61D4-EBC2-E961-E033-A27486040088',
            'datVyst' => '2020-12-01',
            'poznam' => 'Tržby z prodeje služeb',
            'popis' => 'Tržby z prodeje služeb',
            'mena' => 'code:CZK',
            'typDokl' => 'code:FAKTURA'
                ], $this->object->invoiceInfo());
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::domLMTotalToArray
     */
    public function testdomLMTotalToArray() {
//        $this->assertEquals([], $this->object->domLMTotalToArray());
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Imap2AF\Convertor::domInvoiceItemToArray
     */
    public function testdomInvoiceItemToArray() {
//        $this->assertEquals([], $this->object->domInvoiceItemToArray($this->object->getXmlDomDocument()->getElementsByTagName('InvoiceLine')));
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
