<?php

declare(strict_types=1);

/**
 * This file is part of the Imap2AbraFlexi package
 *
 * https://github.com/VitexSoftware/AbraFlexi-email-importer
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Imap2AF;

use AbraFlexi\Imap2AF\Importer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-12-02 at 18:09:08.
 */
class ImporterTest extends \PHPUnit\Framework\TestCase
{
    protected Importer $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Importer('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::importIsdocFiles
     *
     * @todo   Implement testimportIsdocFiles().
     */
    public function testimportIsdocFiles(): void
    {
        $this->assertEquals('', $this->object->importIsdocFiles());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::xmlDomToInvoice
     *
     * @todo   Implement testxmlDomToInvoice().
     */
    public function testxmlDomToInvoice(): void
    {
        $this->assertEquals('', $this->object->xmlDomToInvoice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::invoiceItems
     *
     * @todo   Implement testinvoiceItems().
     */
    public function testinvoiceItems(): void
    {
        $this->assertEquals('', $this->object->invoiceItems());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::domInvoiceItemToArray
     *
     * @todo   Implement testdomInvoiceItemToArray().
     */
    public function testdomInvoiceItemToArray(): void
    {
        $this->assertEquals('', $this->object->domInvoiceItemToArray());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::importInvoiceItems
     *
     * @todo   Implement testimportInvoiceItems().
     */
    public function testimportInvoiceItems(): void
    {
        $this->assertEquals('', $this->object->importInvoiceItems());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::importInvoice
     *
     * @todo   Implement testimportInvoice().
     */
    public function testimportInvoice(): void
    {
        $this->assertEquals('', $this->object->importInvoice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::isForMe
     *
     * @todo   Implement testisForMe().
     */
    public function testisForMe(): void
    {
        $this->assertEquals('', $this->object->isForMe());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::mainLoop
     *
     * @todo   Implement testmainLoop().
     */
    public function testmainLoop(): void
    {
        $this->assertEquals('', $this->object->mainLoop());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::handleMeasureUnit
     *
     * @todo   Implement testhandleMeasureUnit().
     */
    public function testhandleMeasureUnit(): void
    {
        $this->assertEquals('', $this->object->handleMeasureUnit());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::addItemToStorage
     *
     * @todo   Implement testaddItemToStorage().
     */
    public function testaddItemToStorage(): void
    {
        $this->assertEquals('', $this->object->addItemToStorage());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::cleanUp
     *
     * @todo   Implement testcleanUp().
     */
    public function testcleanUp(): void
    {
        $this->assertEquals('', $this->object->cleanUp());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::abraFlexiPricelistPresence
     *
     * @todo   Implement testabraFlexiPricelistPresence().
     */
    public function testabraFlexiPricelistPresence(): void
    {
        $this->assertEquals('', $this->object->abraFlexiPricelistPresence());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::addItemToPriceList
     *
     * @todo   Implement testaddItemToPriceList().
     */
    public function testaddItemToPriceList(): void
    {
        $this->assertEquals('', $this->object->addItemToPriceList());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::getSuplierAbraFlexiID
     *
     * @todo   Implement testgetSuplierAbraFlexiID().
     */
    public function testgetSuplierAbraFlexiID(): void
    {
        $this->assertEquals('', $this->object->getSuplierAbraFlexiID());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::getPaymentMeans
     *
     * @todo   Implement testgetPaymentMeans().
     */
    public function testgetPaymentMeans(): void
    {
        $this->assertEquals('', $this->object->getPaymentMeans());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::abraFlexiSuplierPresence
     *
     * @todo   Implement testabraFlexiSuplierPresence().
     */
    public function testabraFlexiSuplierPresence(): void
    {
        $this->assertEquals('', $this->object->abraFlexiSuplierPresence());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::getInvoiceInfo
     *
     * @todo   Implement testgetInvoiceInfo().
     */
    public function testgetInvoiceInfo(): void
    {
        $this->assertEquals('', $this->object->getInvoiceInfo());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::domLMTotalToArray
     *
     * @todo   Implement testdomLMTotalToArray().
     */
    public function testdomLMTotalToArray(): void
    {
        $this->assertEquals('', $this->object->domLMTotalToArray());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::isKnownInvoice
     *
     * @todo   Implement testisKnownInvoice().
     */
    public function testisKnownInvoice(): void
    {
        $this->assertEquals('', $this->object->isKnownInvoice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::unpackIsdocX
     *
     * @todo   Implement testunpackIsdocX().
     */
    public function testunpackIsdocX(): void
    {
        $this->assertEquals('', $this->object->unpackIsdocX());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::isConnected
     *
     * @todo   Implement testisConnected().
     */
    public function testisConnected(): void
    {
        $this->assertEquals('', $this->object->isConnected());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::createLabel
     *
     * @todo   Implement testcreateLabel().
     */
    public function testcreateLabel(): void
    {
        $this->assertEquals('', $this->object->createLabel());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::recountForPricelist
     *
     * @todo   Implement testrecountForPricelist().
     */
    public function testrecountForPricelist(): void
    {
        $this->assertEquals('', $this->object->recountForPricelist());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::addRecountedPrice
     *
     * @todo   Implement testaddRecountedPrice().
     */
    public function testaddRecountedPrice(): void
    {
        $this->assertEquals('', $this->object->addRecountedPrice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::conf
     *
     * @todo   Implement testconf().
     */
    public function testconf(): void
    {
        $this->assertEquals('', $this->object->conf());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::checkSetup
     */
    public function testcheckSetup(): void
    {
        $this->assertTrue($this->object->checkSetup());
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::checkStorage
     *
     * @todo   Implement testcheckStorage().
     */
    public function testcheckStorage(): void
    {
        $this->assertEquals('', $this->object->checkStorage());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Importer::checkBank
     *
     * @todo   Implement testcheckBank().
     */
    public function testcheckBank(): void
    {
        $this->assertEquals('', $this->object->checkBank());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
