<?php

namespace Test\AbraFlexi\Imap2AF;

use AbraFlexi\Imap2AF\MailImporter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-02-17 at 22:32:34.
 */
class MailImporterTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var MailImporter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new MailImporter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers AbraFlexi\Imap2AF\MailImporter::importMails
     * @todo   Implement testimportMails().
     */
    public function testimportMails()
    {
        $this->assertEquals('', $this->object->importMails());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Imap2AF\MailImporter::moveMessageToDoneFolder
     * @todo   Implement testmoveMessageToDoneFolder().
     */
    public function testmoveMessageToDoneFolder()
    {
        $this->assertEquals('', $this->object->moveMessageToDoneFolder());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Imap2AF\MailImporter::alreadyKnownInvoice
     * @todo   Implement testalreadyKnownInvoice().
     */
    public function testalreadyKnownInvoice()
    {
        $this->assertEquals('', $this->object->alreadyKnownInvoice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Imap2AF\MailImporter::cleanUp
     * @todo   Implement testcleanUp().
     */
    public function testcleanUp()
    {
        $this->assertEquals('', $this->object->cleanUp());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
