<?php

declare(strict_types=1);

/**
 * This file is part of the Imap2AbraFlexi package
 *
 * https://github.com/VitexSoftware/AbraFlexi-email-importer
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Imap2AF;

use AbraFlexi\Imap2AF\Mailboxer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-12-02 at 18:09:08.
 */
class MailboxerTest extends \PHPUnit\Framework\TestCase
{
    protected Mailboxer $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Mailboxer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Mailboxer::setUp
     *
     * @todo   Implement testsetUp().
     */
    public function testsetUp(): void
    {
        $this->assertEquals('', $this->object->setUp());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Mailboxer::setupProperty
     *
     * @todo   Implement testsetupProperty().
     */
    public function testsetupProperty(): void
    {
        $this->assertEquals('', $this->object->setupProperty());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Mailboxer::pullIsdocs
     *
     * @todo   Implement testpullIsdocs().
     */
    public function testpullIsdocs(): void
    {
        $this->assertEquals('', $this->object->pullIsdocs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Mailboxer::saveIsdocs
     *
     * @todo   Implement testsaveIsdocs().
     */
    public function testsaveIsdocs(): void
    {
        $this->assertEquals('', $this->object->saveIsdocs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Mailboxer::addStatusMessage
     *
     * @todo   Implement testaddStatusMessage().
     */
    public function testaddStatusMessage(): void
    {
        $this->assertEquals('', $this->object->addStatusMessage());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Mailboxer::getStatusMessages
     *
     * @todo   Implement testgetStatusMessages().
     */
    public function testgetStatusMessages(): void
    {
        $this->assertEquals('', $this->object->getStatusMessages());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Mailboxer::cleanSatatusMessages
     *
     * @todo   Implement testcleanSatatusMessages().
     */
    public function testcleanSatatusMessages(): void
    {
        $this->assertEquals('', $this->object->cleanSatatusMessages());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Mailboxer::getLogger
     *
     * @todo   Implement testgetLogger().
     */
    public function testgetLogger(): void
    {
        $this->assertEquals('', $this->object->getLogger());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\Mailboxer::logBanner
     *
     * @todo   Implement testlogBanner().
     */
    public function testlogBanner(): void
    {
        $this->assertEquals('', $this->object->logBanner());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
