<?php

declare(strict_types=1);

/**
 * This file is part of the Imap2AbraFlexi package
 *
 * https://github.com/VitexSoftware/AbraFlexi-email-importer
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Imap2AF;

use AbraFlexi\Imap2AF\MailImporter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-02-17 at 22:32:34.
 */
class MailImporterTest extends \PHPUnit\Framework\TestCase
{
    protected MailImporter $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new MailImporter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Imap2AF\MailImporter::importMails
     *
     * @todo   Implement testimportMails().
     */
    public function testimportMails(): void
    {
        $this->assertEquals('', $this->object->importMails());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\MailImporter::moveMessageToDoneFolder
     *
     * @todo   Implement testmoveMessageToDoneFolder().
     */
    public function testmoveMessageToDoneFolder(): void
    {
        $this->assertEquals('', $this->object->moveMessageToDoneFolder());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\MailImporter::alreadyKnownInvoice
     *
     * @todo   Implement testalreadyKnownInvoice().
     */
    public function testalreadyKnownInvoice(): void
    {
        $this->assertEquals('', $this->object->alreadyKnownInvoice());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Imap2AF\MailImporter::cleanUp
     *
     * @todo   Implement testcleanUp().
     */
    public function testcleanUp(): void
    {
        $this->assertEquals('', $this->object->cleanUp());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
